language: node_js

node_js:
  - 9.8.0
os: osx

sudo: required

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"
    - "$HOME/.npm/_prebuilds"

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

# before_install:
#   - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash"

script:
  - npm run deploy_app

# after_success:
#   - fossa test